### PR TITLE
support Go Modules

### PR DESCRIPTION
**Pull request by ghost**
This PR enables Cali to be used with Go Modules.  The main change is correcting the import for `github.com/sirupsen/logrus` to be entirely lowercase as that is what it reports.

Without this PR I am unable to import Cali in a project that is using Go Modules:

```
go: github.com/wheresalice/datali imports
        github.com/wheresalice/datali/cmd imports
        github.com/skybet/cali imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```

(although I could probably handle that in my `go.mod` file locally)

### CODE REVIEW

**Comment by WheresAlice** [comment]
I **think** the tests failing here are unrelated to my change, but it has highlighted that the Travis CI pipeline needs updating to use Go Modules. Maybe.

**Comment by WheresAlice** [comment]
I've raised #57 to cover the build failing

**Comment by WheresAlice** [comment]
Finally!  Some passing tests!

This PR will now close #57 as well as supporting Go modules

**Comment by lucymhdavies** [comment]
Yay! Thanks :)

I've just added 190d65b929ccec62d7d10a26e359a4526a1803d9 to `master` so Travis will check against Go 1.13. Mind rebasing, just to make sure it works there too, then I'll merge + release :)

**Comment by lucymhdavies** [comment]
Now available as v0.4.0 :)

**Comment by ghost** [comment]
Yep, my app is now pulling in 0.4.0 of Cali and successfully building using Go modules.

Thank you!

**Pull request merged**
