### PR TITLE
Removed .gitignore

### PR DESCRIPTION
**Pull request by edupo**
I think this ignore file looks more as a user [global git ignore file](https://gist.github.com/mitchallen/2437727).

### CODE REVIEW

**Comment by WheresAlice** [comment]
I tend to agree that these should be in a user global git ignore file, but leaving this in place isn't causing any problems and makes it harder for new contributors to commit things they shouldn't - so I'd be tempted to leave it in place.

**Comment by lucymhdavies** [comment]
I also agree that global git ignore files are useful, but that repo-specific files are useful for new contributors.

That being said, there's isn't really all that much repo-specific in this one, so we can get rid of most of it.

```
# Test binary, build with `go test -c`	
*.test
```
Probably worth keeping this one.

```
# Output of the go coverage tool, specifically when used with LiteIDE	
*.out
```

Probably worth keeping this too.

**Comment by lucymhdavies** [comment]
I think it originally started as https://github.com/github/gitignore/blob/master/Go.gitignore

**Comment by lucymhdavies** [comment]
Just created a new GitHub repo, and let GitHub create the `.gitignore` file for me:

screen shot 2018-04-07 at 20 13 38


It came up with:

```
# Binaries for programs and plugins
*.exe
*.dll
*.so
*.dylib

# Test binary, build with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Project-local glide cache, RE: https://github.com/Masterminds/glide/issues/736
.glide/
```

So yes, it's https://github.com/github/gitignore/blob/master/Go.gitignore


But the only relevant ones for Cali are:

```
# Test binary, build with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out
```

So I'm going to close this, update gitignore to just those

**Pull request closed without merging**
